name: appsandalias
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/animal1.jpeg
  - assets/images/animal2.png
  - assets/images/animal3.jpeg
  - assets/images/animalGaivota2.jpg
  - assets/images/animalGaivota3.jpg
  - assets/images/GaivotaIntro.jpg
  - assets/images/PraiaMaresias.jpg
  - assets/images/PraiaEnseada.jpeg
  - assets/images/PraiaCouves.jpg
  - assets/images/PraiaJuliao.jpg
  - assets/images/trilha7.jpg
  - assets/images/trilhabananas.jpg
  - assets/images/trilhafortaleza.jpg
  - assets/images/trilhabonete.jpg
  - assets/images/MaresiasIntro.jpg
  - assets/images/CapelaMaresias.jpg
  - assets/images/PoçoCaetano.jpg
  - assets/images/ImgMaresias1.jpg
  - assets/images/ImgMaresias2.jpg
  - assets/images/ImgMaresias3.jpg
  - assets/images/EnseadaIntro.jpg
  - assets/images/ImgEnseada1.jpg
  - assets/images/ImgEnseada2.jpg
  - assets/images/ImgEnseada3.jpg
  - assets/images/mirante.jpg
  - assets/images/Acqua.jpg
  - assets/images/Trilha7Intro.jpg
  - assets/images/Trilha7mapa.jpg
  - assets/images/TrilhaBananasIntro.jpg
  - assets/images/TrilhaBananasmapa.jpg
  

